apiVersion: v1
kind: Secret
metadata:
  name: cloudns-dyndns      
  namespace: standard
type: Opaque
stringData:
  dynurl: "https://ipv4.cloudns.net/api/dynamicURL/?q=MTM4NTIzODg6ODE4OTk2NjEzOjE5MjJhNzRhZjEzNTI3NDYyYTI5OTk5MmM4NjVkMjRlMWUzMzQyYzY0Y2FlNDY3Y2NkMTI3NzA4MzExMjYwYWQ"