apiVersion: batch/v1
kind: CronJob
metadata:
  name: cloudns-update
spec:
  schedule: {{ .Values.cronjob.schedule | quote }}     
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: updater
              image: "{{ .Values.cronjob.image.repository }}:{{ .Values.cronjob.image.tag | default .Chart.AppVersion }}" 
              command:
                - sh
                - -c
                - 'curl -s "$DYNURL"'
              env:
                - name: DYNURL
                  valueFrom:
                    secretKeyRef:
                      name: cloudns-dyndns
                      key: dynurl