apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
spec:
  replicas: {{ .Values.fastapi.replicas }}
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          ports:
            - containerPort: {{ .Values.service.port }}