apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
spec:
  replicas: {{ .Values.pgadmin.replicas }}
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
        - name: pgadmin
          image: {{ .Values.pgadmin.image }}
          ports:
            - containerPort: 80 
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              value: {{ .Values.pgadmin.email | quote }}
            - name: PGADMIN_DEFAULT_PASSWORD
              value: {{ .Values.pgadmin.password | quote }}