apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  serviceName: db
  replicas: {{ .Values.postgres.replicas }}
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.image.repository.}}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config-exam
            - secretRef:
                name: postgres-secret-exam
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: {{ .Values.postgres.storageClass | quote}}
        resources:
          requests:
            storage: {{ .Values.postgres.storge }}